### ISSUE TITLE
check_license never expires!

### ISSUE THREAD

**Issue by jpvhack** [slauger/check_netscaler#29]
Hello!,

Great plugin, but check license always shows "never expires".

When using user nsmonitor (NetScaler 11.0):

./check_netscaler.pl -H netscaler -s -C license -n FID__xxx_xxx__xxx.lic -u nsroot  -p nsroot -w 1  -c 1
NetScaler OK - license: CNS_SSE_SERVER never expires; CNS_V5_SERVER never expires;¿?¿?¿

**Comment by slauger** [comment]
Hi,

thanks for your feedback!

What type of license file do you have on your appliance? Only CSP (Citrix Service Provider) or Evaluation licenses have a expiry date. 

The check extracts the expiry date from lines in the license files starting with `INCREMENT`. If you have a license which will never expire, your license file should have a "permanent" entry instead of a expiry date in that lines. e.g.
```
root@netscaler01# grep ^INCREMENT /nsconfig/license/*.lic
/nsconfig/license/FID_xxxx_2a97.lic:INCREMENT CNS_V1000_SERVER CITRIX 2017.0303 18-jan-2018 1 \
/nsconfig/license/FID_xxxx_2a97.lic:INCREMENT CNS_SPE_SERVER CITRIX 2017.0303 18-jan-2018 1 \
/nsconfig/license/FID_xxxx_2a99.lic:INCREMENT CAG_SSLVPN_CCU CITRIX 2017.0215 18-jan-2018 100 \
/nsconfig/license/FID_xxxx_2a99.lic:INCREMENT CAG_AAC_CCU CITRIX 2017.0215 18-jan-2018 100 \
/nsconfig/license/FID_xxxx_2a99.lic:INCREMENT CNS_SSLVPN_CCU CITRIX 2017.0215 18-jan-2018 100 \
```

**Comment by jpvhack** [comment]
Hi,

You're right. I have to see how to monitor the license file before it expires in a year.

**Comment by slauger** [comment]
Do you mean the expiry date for your SA (software assurance)? 

The license expiry date and the expiry date for the SA are two different things.

If you have a expired CSP license your NetScaler will disable nearly every feature after the next reboot.
A expired SA date doesn't matter, as long you won't try to upgrade to a newer major/minor version, which was released after the SA expiry date.
