### ISSUE TITLE
Nitro API - command for uptime

### ISSUE THREAD

**Issue by nicoh88** [slauger/check_netscaler#3]
Does anyone have a **command reference** for NetScaler Nitro API?
Or the command for uptime?

**Comment by slauger** [comment]
Hi,

please have a look at the NITRO documentation -> http://NSIP/nitro-rest.tgz

You can use "starttime" or "timesincestart" from the system endpoint.

system: -> starttime <String>
Time when the NetScaler appliance was last started.

system: timesincestart <string>
Seconds since the NetScaler appliance started.

**Comment by slauger** [comment]
You also can find the download link in the admin GUI on the "Download" page (top right hand side).

**Comment by nicoh88** [comment]
Thank you, "system: timesincestart" is it.

**Comment by slauger** [comment]
I'm going to close this. If you still need assistance just let me know.
