### ISSUE TITLE
Alive? 12.1: Build 51.19 ?

### ISSUE THREAD

**Issue by tuxtown** [slauger/check_netscaler#42]
Is this plugin still alive? On a new SDX with 12.1: Build 51.19 all checks give me:

debug: target url is http://x.y.z//nitro/v1/config/nshardware
debug: response of request is:
$VAR1 = '{ "errorcode": 10005, "message": "Invalid Resource", "severity": "ERROR" }';
NetScaler UNKNOWN - { "errorcode": 10005, "message": "Invalid Resource", "severity": "ERROR" }

**Comment by slauger** [comment]
Yep, the plugin is still maintained and also works with 12.1.

Have a look at #16. The SDX may use the API version 2. Could you test if it works when using the `--api='v2'` switch?

I never had the chance to test the plugin against a SDX directly (only some VPX instances running ON a SDX). I would be interested to enhance the support for SDX instances if you are willing to help.

**Comment by tuxtown** [comment]
That doesn't make a difference. But I noticed the plugin does work for a vpx on this sdx.

**Comment by slauger** [comment]
The problem is that Citrix does not provide any SDX specific NITRO API docs (NITRO v2.x). I already contacted the guys from Citrix a few months ago, but it seems like Citrix is not interested in helping/sponsoring OSS projects. 

I need some kind of development environment or at least some example api respones (e.g. from curl) to check what API endpoints are available (and maybe what we need to change in `check_netscaler` to support the API 2.x).

**Comment by slauger** [comment]
Closed because of missing response. You can still reply to this issue if you have any further problems or comments.
